package generator

import (
	"fmt"
	"strings"
)

// GoFrameGenerator GoFrame 框架适配生成器
type GoFrameGenerator struct{}

func (g *GoFrameGenerator) Generate(config *Config, entries []*EnumEntry) ([]*OutputFile, error) {
	defaultMsg := config.DefaultHttpMsg
	if defaultMsg == "" {
		defaultMsg = "服务繁忙"
	}

	files := []*OutputFile{
		g.generateTypes(config),
		g.generateErrors(config, entries, defaultMsg),
		g.generateMiddleware(config),
	}
	return files, nil
}

func (g *GoFrameGenerator) generateTypes(config *Config) *OutputFile {
	var b strings.Builder

	fmt.Fprintf(&b, `// Code generated by generrorx; DO NOT EDIT.

package %s

import (
	"fmt"

	"github.com/gogf/gf/v2/errors/gcode"
	"github.com/gogf/gf/v2/errors/gerror"
)

// Error 统一错误类型（GoFrame 适配）
type Error struct {
	code     int    // 后端错误码（细粒度，日志用）
	name     string // 枚举名（日志用）
	httpCode int    // HTTP 状态码（返回前端）
	httpMsg  string // 前端看到的消息
	cause    error  // 底层错误
}

func newErr(code int, name string, httpCode int, httpMsg string) *Error {
	return &Error{code: code, name: name, httpCode: httpCode, httpMsg: httpMsg}
}

// Error 实现 error 接口
func (e *Error) Error() string {
	if e == nil {
		return ""
	}
	if e.cause != nil {
		return fmt.Sprintf("[%%d/%%s] %%v", e.code, e.name, e.cause)
	}
	return fmt.Sprintf("[%%d/%%s]", e.code, e.name)
}

// Code 返回后端错误码
func (e *Error) Code() int { return e.code }

// Name 返回枚举名
func (e *Error) Name() string { return e.name }

// HttpCode 返回 HTTP 状态码
func (e *Error) HttpCode() int { return e.httpCode }

// HttpMsg 返回前端消息
func (e *Error) HttpMsg() string { return e.httpMsg }

// Unwrap 支持 errors.Unwrap
func (e *Error) Unwrap() error { return e.cause }

// Wrap 包裹底层错误
func (e *Error) Wrap(err error) *Error {
	return &Error{
		code:     e.code,
		name:     e.name,
		httpCode: e.httpCode,
		httpMsg:  e.httpMsg,
		cause:    err,
	}
}

// WrapMsg 包裹底层错误并覆盖前端消息
func (e *Error) WrapMsg(err error, httpMsg string) *Error {
	return &Error{
		code:     e.code,
		name:     e.name,
		httpCode: e.httpCode,
		httpMsg:  httpMsg,
		cause:    err,
	}
}

// WithMsg 覆盖前端消息
func (e *Error) WithMsg(httpMsg string) *Error {
	return &Error{
		code:     e.code,
		name:     e.name,
		httpCode: e.httpCode,
		httpMsg:  httpMsg,
		cause:    e.cause,
	}
}

// Is 支持 errors.Is
func (e *Error) Is(target error) bool {
	if t, ok := target.(*Error); ok {
		return e.code == t.code
	}
	return false
}

// ToGError 转换为 GoFrame 的 gerror（用于需要和 GoFrame 生态集成的场景）
func (e *Error) ToGError() error {
	return gerror.NewCode(gcode.New(e.httpCode, e.httpMsg, ""), e.Error())
}
`, config.PackageName)

	return &OutputFile{
		Path:    "./types.go",
		Content: b.String(),
	}
}

func (g *GoFrameGenerator) generateErrors(config *Config, entries []*EnumEntry, defaultMsg string) *OutputFile {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by generrorx; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", config.PackageName)

	var bizEntries, internalEntries []*EnumEntry
	for _, e := range entries {
		if e.IsInternal() {
			internalEntries = append(internalEntries, e)
		} else {
			bizEntries = append(bizEntries, e)
		}
	}

	if len(bizEntries) > 0 {
		fmt.Fprintf(&b, "// ====== 业务错误（返回前端）======\n")
		fmt.Fprintf(&b, "var (\n")
		for _, e := range bizEntries {
			fmt.Fprintf(&b, "\t%s = newErr(%d, %q, %d, %q)\n",
				e.VarName(), e.Code, e.Name, e.HttpCode, e.HttpMsg)
		}
		fmt.Fprintf(&b, ")\n\n")
	}

	if len(internalEntries) > 0 {
		fmt.Fprintf(&b, "// ====== 内部错误（前端统一返回 500）======\n")
		fmt.Fprintf(&b, "var (\n")
		for _, e := range internalEntries {
			comment := e.Comment
			if comment != "" {
				comment = " // " + comment
			}
			fmt.Fprintf(&b, "\t%s = newErr(%d, %q, 500, %q)%s\n",
				e.VarName(), e.Code, e.Name, defaultMsg, comment)
		}
		fmt.Fprintf(&b, ")\n")
	}

	return &OutputFile{
		Path:    "./errors_gen.go",
		Content: b.String(),
	}
}

func (g *GoFrameGenerator) generateMiddleware(config *Config) *OutputFile {
	var b strings.Builder

	fmt.Fprintf(&b, `// Code generated by generrorx; DO NOT EDIT.

package %s

import (
	"net/http"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

// ErrorMiddleware GoFrame 统一错误处理中间件
// 使用方式：
//
//	s.BindMiddlewareDefault(errorx.ErrorMiddleware)
func ErrorMiddleware(r *ghttp.Request) {
	r.Middleware.Next()

	if err := r.GetError(); err != nil {
		r.SetError(nil) // 清除错误，避免框架默认处理

		if e, ok := err.(*Error); ok {
			// 后端日志
			g.Log().Errorf(r.Context(), "%%v", e)

			// 前端响应
			r.Response.WriteStatus(e.HttpCode())
			r.Response.WriteJson(g.Map{
				"code": e.HttpCode(),
				"msg":  e.HttpMsg(),
			})
		} else {
			g.Log().Errorf(r.Context(), "unknown error: %%v", err)
			r.Response.WriteStatus(http.StatusInternalServerError)
			r.Response.WriteJson(g.Map{
				"code": http.StatusInternalServerError,
				"msg":  "服务繁忙",
			})
		}
	}
}
`, config.PackageName)

	return &OutputFile{
		Path:    "./middleware.go",
		Content: b.String(),
	}
}
